application: pondnext
version: 1
runtime: python
api_version: 1

handlers:
- url: /cache.manifest
  static_files: static/cache.manifest
  upload: static/cache.manifest
  mime_type: text/cache-manifest
- url: /
  script: main.py
- url: /proxy.php
  script: main.py
- url: /
  static_dir: static/
  expiration: 1
